# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "debi"

  config.vbguest.auto_update = false  

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081
  
  config.vm.define "debi" do |debi|
    debi.vm.provider "virtualbox" do |vb|
      vb.name   = "debi"
      vb.memory = "512"
    end

    debi.vm.provision "shell", inline: <<-SHELL
      sudo sed -ie "s/#PasswordAuthentication yes/PasswordAuthentication no/g"  /etc/ssh/sshd_config
      sudo systemctl restart sshd

      sudo cp /vagrant/index.html /home/vagrant
      sudo cp /vagrant/index.php /home/vagrant
      sudo cp /vagrant/web1.conf /home/vagrant
      sudo cp /vagrant/web2.conf /home/vagrant
    SHELL
    debi.vm.provision "shell", path: "script.sh"
  end
end
