# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "taksama/centos8-lamp"
  config.vm.box_version = "1.0.2"
  config.vm.hostname = "centos8"
 
  config.vm.define "web_centos8" do |web_centos8|
    web_centos8.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    web_centos8.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
    web_centos8.vm.network "private_network", ip: "172.31.1.10"

    web_centos8.vm.provider "virtualbox" do |vb|
      vb.name = "web_centos8"
      vb.memory = "512"
    end

    web_centos8.vm.provision "shell", inline: <<-SHELL
      sudo mkdir -p /var/www/web{1,2}.org/html
      sudo cp /vagrant/index.html /var/www/web1.org/html
      sudo cp /vagrant/index.php /var/www/web2.org/html
      sudo chmod -R 755 /var/www
      sudo sed -i '/Listen 80/a Listen 81' /etc/httpd/conf/httpd.conf
      sudo cp /vagrant/web.conf /etc/httpd/conf.d/
      sudo systemctl restart httpd
    SHELL
  end
end
