# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 2048
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = 'playbook.yaml'
    ansible.become = true
    ansible.inventory_path = "inventory/hosts"
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master.puppet"
    master.vm.network "private_network", ip: "172.31.4.20"
    
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
    end
    master.vm.synced_folder "files", "/home/vagrant/files", type: "rsync"
    master.vm.synced_folder "puppet_conf/pp_path", "/etc/profile.d/", type: "rsync"
    master.vm.synced_folder "puppet_conf/master", "/etc/puppetlabs/puppet", type: "rsync"
    master.vm.synced_folder "puppet_conf/r10k", "/etc/puppetlabs/r10k", type: "rsync"
  end

  config.vm.define "slave1" do |slave1|
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    slave1.vm.network "private_network", ip: "172.31.4.10"
    slave1.vm.provider "virtualbox" do |vb|
      vb.name = "slave1"
    end
    slave1.vm.synced_folder "puppet_conf/pp_path", "/etc/profile.d/", type: "rsync"
    slave1.vm.synced_folder "puppet_conf/slave1", "/etc/puppetlabs/puppet", type: "rsync"
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
    slave2.vm.network "private_network", ip: "172.31.4.11"
    slave2.vm.provider "virtualbox" do |vb|
      vb.name = "slave2"
    end
    slave2.vm.synced_folder "puppet_conf/pp_path", "/etc/profile.d/", type: "rsync"
    slave2.vm.synced_folder "puppet_conf/slave2", "/etc/puppetlabs/puppet", type: "rsync"
  end

  config.vm.define "mineserver" do |mineserver|
    mineserver.vm.hostname = "mineserver.puppet"
    mineserver.vm.network "private_network", ip: "172.31.4.12"
    mineserver.vm.provider "virtualbox" do |vb|
      vb.name = "mineserver"
    end
    mineserver.vm.synced_folder "puppet_conf/pp_path", "/etc/profile.d/", type: "rsync"
    mineserver.vm.synced_folder "puppet_conf/mineserver", "/etc/puppetlabs/puppet", type: "rsync"
  end
end
