FROM sonatype/nexus3:3.20.1
SHELL ["/bin/bash", "-c"]
COPY ./files/nexus /scripts
USER root
RUN chmod -R 777 /scripts \
 && echo "nexus.onboarding.enabled=false" >> /nexus-data/etc/nexus.properties
ENTRYPOINT /scripts/entry_script.sh
